### ISSUE TITLE
how to make this slider auto move?

### ISSUE THREAD

**Issue by dineshsuthar92** [tulios/jquery.silver_track#2]
Hi,
I have used this slider in my website but I need this slider to auto-move as soon as the webpage is loaded.Currently we have to click on slider to move.

Please help me in this regard.

Thanks !

**Comment by tulios** [comment]
Hi @dineshsuthar92 now silver track has a circular navigator plugin which allows auto play, please take a look at  http://tulios.github.io/jquery.silver_track/plugins/circular-navigator.html
