### ISSUE TITLE
auto play does not work in IE

### ISSUE THREAD

**Issue by fineartist99** [tulios/jquery.silver_track#24]
See for yourself http://dev.radiuscleveland.com/thecarmongroup/slide/client-logos.html 

Hopefully someone can provide a solution for my problem.  Thanks in advance.

**Comment by tulios** [comment]
Hi @fineartist99, this error seems to be the use of `requestAnimationFrame` I didn't test though. It can easily  be patched, I'm away of my computer now but as soon as I get in the office I'll post a solution here.

**Comment by fineartist99** [comment]
thank you so much

**Comment by tulios** [comment]
Hi @fineartist99, try this code:

```js
// requestAnimationFrame() shim by Paul Irish
// http://paulirish.com/2011/requestanimationframe-for-smart-animating/
window.requestAnimFrame = (function() {
	return  window.requestAnimationFrame   ||
			window.webkitRequestAnimationFrame ||
			window.mozRequestAnimationFrame    ||
			window.oRequestAnimationFrame      ||
			window.msRequestAnimationFrame     ||
			function(/* function */ callback, /* DOMElement */ element){
				window.setTimeout(callback, 1000 / 60);
			};
})();
```

You must include it before the silver track code.

**Comment by fineartist99** [comment]
I'm guessing you wanted me to add it to the example7.js file, I altered that file and it's still not working.  I changed the name of the file and altered the test page you saw to relink to the new named file and still not working.  Let me know if there was something else that I should've done or if I did something wrong on the example7.js file.  Here's a link to download my js file http://dev.radiuscleveland.com/thecarmongroup/slide/example/js/example7n.js.zip

**Comment by tulios** [comment]
Your file is correct, my shim is wrong. The correct version is:

change `window.requestAnimFrame ` with `window.requestAnimationFrame`, the full version:

```js
window.requestAnimationFrame = (function() {
    return  window.requestAnimationFrame   ||
            window.webkitRequestAnimationFrame ||
            window.mozRequestAnimationFrame    ||
            window.oRequestAnimationFrame      ||
            window.msRequestAnimationFrame     ||
            function(/* function */ callback, /* DOMElement */ element){
                window.setTimeout(callback, 1000 / 60);
            };
})();
```

**Comment by fineartist99** [comment]
nope, that did not work either - see here
http://dev.radiuscleveland.com/thecarmongroup/slide/client-logos2.html

also, I'd like to mention that at the end of the carousel it doesn't continue with the start.  You know what I mean?  It's not infinite as they say.  Check out the link in a different browser and you'll see what I mean.  In IE the carousel stops at the end.  Thank you so much for your help, hopefully we can get this working correctly in IE

**Comment by tulios** [comment]
I tested your link in Chrome and everything works as expected (circular navigation), I will need more time to test in other browser and track this bug :/

**Comment by fineartist99** [comment]
thanks, keep me updated with bug in IE

**Comment by tulios** [comment]
This bug is probably caused by issue #26
