### ISSUE TITLE
Issue with jquery.silver_track.circular_navigator.js with IE

### ISSUE THREAD

**Issue by ligerbi** [tulios/jquery.silver_track#26]
While trying to use the circular navigator with IE I saw that the plugin is stuck after the first pulse.
I fouded out that in jquery.silver_track.circular_navigator.js (row 211) there is usage with "Math.trunc" which not supported in IE.
After changing it to "Math.floor" it started work well.

**Comment by tulios** [comment]
Hi @ligerbi thanks for the issue. @MarcosOcf can you make the change? Actually, we shouldn't be using ES6 features in this plugin since the support is really low at the moment (http://kangax.github.io/compat-table/es6/#Math.trunc)
