### ISSUE TITLE
Which files to include?

### ISSUE THREAD

**Issue by winternet-studio** [tulios/jquery.silver_track#32]
Which js and css files are needed to in order to use the plugin? Documentation says nothing about it and the examples has a whole slew of files of which I have no idea what each one does... I just want to use the track plugin.

**Comment by tulios** [comment]
You can take a look at the "Getting started" guide:

http://tulios.github.io/jquery.silver_track/how_tos/getting-started.html

**Comment by winternet-studio** [comment]
I don't see anything about files to include or any description of files there...??

**Comment by tulios** [comment]
Silver track is modular, so you have to include the library + any plugins you are using, for example:

https://github.com/tulios/jquery.silver_track/blob/master/src/jquery.silver_track.js
https://github.com/tulios/jquery.silver_track/blob/master/src/plugins/jquery.silver_track.navigator.js

**Comment by winternet-studio** [comment]
Yes, but in the library you also have these files without describing what they do or when I should use them:

/lib/jquery-easing-1.3.0.js
/lib/modernizr_mediaqueries.js
/lib/responsive-hub.js

**Comment by tulios** [comment]
The files in lib are dependencies of some of the plugins, for example, the `Css3Animation` plugin depends on `modernizr_mediaqueries` and this is documented in the plugin page http://tulios.github.io/jquery.silver_track/plugins/css3-animation.html

The minimum setup for silver track is the `jquery.silver_track.js` file and some CSS as described by the getting started guide.

Feel free to ask more questions if it's not clear.
Thanks.
