### ISSUE TITLE
Plugin 'cssAnimation' ignores animate flag when restarting

### ISSUE THREAD

**Issue by MarcosOcf** [tulios/jquery.silver_track#7]
I think that some actions in 'cssAnimation' plugin are maybe different than they should be by SilverTrack default.

1- when you try to restart your track without animation, the behavior is equal as animated.

```javascript
this.track.restart({page: 3, animate: false})
``` 
or
```javascript
this.track.restart({keepCurrentPage: 3, animate: false})
``` 
2- consider 'current page' as 3, and you try to restart directly to page 2..

2.1  ..with animation, the track should animate from page 3 to page 2, and the current behavior is restart to page 1 and then animate for page 2.

```javascript
this.track.restart({page: 2, animate: true})
``` 
2.2  ..without animation, the track should appear directly on page 2, but the current behavior is equal as described in 2.1 with animation, ignoring *animate: false*.

```javascript
this.track.restart({page: 2, animate: false})
``` 

It would help to get a better code in #4 (Plugin for circular navigation) and others.

**Comment by tulios** [comment]
Closed by pull request #8
